In [2]:
import numpy as np
arr=np.linspace(0,20,5)
arr

array([ 0.,  5., 10., 15., 20.])

In [5]:
arr2=np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [7]:
arr3=np.ones((3,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr4=np.random.rand(4,4)
arr4

array([[0.36916674, 0.70083062, 0.54038078, 0.80672383],
       [0.24535144, 0.54731893, 0.47741411, 0.22295954],
       [0.14918256, 0.81239428, 0.36000537, 0.28619432],
       [0.41811801, 0.43571159, 0.58647418, 0.44239899]])

In [13]:
arr5=np.array([1,2,3,4,5])
arr5

print("First element:",arr5[0])
print("Second element:",arr5[1])

First element: 1
Second element: 2


In [18]:
sub_arr=arr5[0:3]
print(sub_arr)
range_val=max(sub_arr)-min(sub_arr)
print("range of elements from 1st to 3rd:",range_val)

[1 2 3]
range of elements for 1st to 3rd: 2


In [20]:
sub_arr2=arr5[1:]
print(sub_arr2)
range_v=max(sub_arr2)-min(sub_arr2)
print("range of elements from 2nd element:",range_v)

[2 3 4 5]
range of elements from 2nd element: 3


In [21]:
sub_arr3=arr5[-2:]
print(sub_arr3)
range_v=max(sub_arr3)-min(sub_arr)
print("range of elements from index -2:",range_v)

[4 5]
range of elements from index -2: 4


In [23]:
import numpy as np
arr1=[1,2,3]
arr2=[4,5,6]

arr_2D=np.array([arr1,arr2])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print("1st row 2nd col element:",arr_2D[0,1])
print("2nd row element:",arr_2D[1])
print("3rd col element:",arr_2D[:,2])


range_row1=max(arr_2D[0])-min(arr_2D[0])
print("Range of element in 1st row:",range_row1)

1st row 2nd col element: 2
2nd row element: [4 5 6]
3rd col element: [3 6]
Range of element in 1st row: 2


In [33]:
sub_arr=arr_2D[0:2,1:3]
print(sub_arr)
range_val=np.max(sub_arr)-np.min(sub_arr)
print("Range of element in 1st and 2nd row with 2nd and 3rd col:",range_val)

[[2 3]
 [5 6]]
Range of element in 1st and 2nd row with 2nd and 3rd col: 4
